version: '3.8'

services:
  db:
    image: postgres:16.2
    container_name: db
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - ${DB_PORT}:5555
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bot_server

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fasttube
    ports:
      - '7777:7777'
    restart: always
    env_file:
      - .env
    volumes:
      - ./:/bot/
    networks:
      - bot_server

networks:
  bot_server:
    driver: "bridge"
