version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bot
    ports:
      - '7777:7777'
    restart: always
    env_file:
      - .env
    volumes:
      - ./:/sm_bot/
    networks:
      - sm-bot

networks:
  sm-bot:
    driver: "bridge"
