"""fssfdsd

Revision ID: 898e8b6b1f0d
Revises: d1a11e847149
Create Date: 2024-11-03 00:42:49.632835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '898e8b6b1f0d'
down_revision: Union[str, None] = 'd1a11e847149'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
